services:
  - type: web
    name: house-price-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/app.py --server.address 0.0.0.0 --server.port $PORT
